# Generated by Django 6.0.2 on 2026-02-17 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cookbook_site", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="rates",
        ),
        migrations.AddField(
            model_name="rate",
            name="recipe",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates",
                to="cookbook_site.recipe",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="savedrecipes",
            unique_together={("user", "recipe")},
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cookbook_site.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="cookbook_site.recipe",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ReicpeIngredient",
        ),
    ]
