# Generated by Django 6.0.2 on 2026-02-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cookbook_site", "0002_remove_recipe_rates_rate_recipe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="recipe_img/"
            ),
        ),
    ]
